name: Building
on:
  push:
    branches: [ master ]
jobs:
  debian-13:
    runs-on: ubuntu-latest
    container:
      image: jeonghanlee/debian13-epics
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "EPICS_BASE:=/usr/local/epics/R7.0.7/base" > configure/RELEASE.local
          make      
  rocky-8:
    runs-on: ubuntu-latest
    container:
      image: jeonghanlee/rocky8-epics
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "EPICS_BASE:=/usr/local/epics/R7.0.7/base" > configure/RELEASE.local
          make
